spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://60.204.201.46:3306/DB01
    username: root
    password: 123456
  redis:
    host: 60.204.201.46
    port: 6379
    password: xjdzy0624.
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 连接池最大空闲数
        max-idle: 8
        min-idle: 0
        # 最长等待时间
        max-wait: 100ms
  servlet:
    multipart:
      enabled: true
      max-file-size: 16MB
      max-request-size: 160MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl